version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.7

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:14.21

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Dependency Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Run Tests!
      - run: npm test

      - coveralls/upload

      - store_artifacts:
          path: ./coverage

workflows:
  build_workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
